### ISSUE TITLE
Add a command so I don't have to click the status bar

### ISSUE THREAD

**Issue by rattrayalex** [shanmuganathan-balaraman/jsonyamlkeynavigator#3]
Hi there, 

This seems like a much-needed extension (see also https://github.com/redhat-developer/vscode-yaml/issues/999 and https://github.com/nidu/vscode-copy-json-path/issues/20). Thank you for developing and sharing it.

I'd like to be able to type "copy json path" or similar in my command palette rather than having to use my mouse to click the status bar. Also sometimes my status bar gets quite cluttered from other extensions.

Is this a feature you'd consider adding?

Thanks!

**Comment by shanmuganathan-balaraman** [comment]
@rattrayalex Good suggestion, will work on this feature for the next release.

**Comment by shanmuganathan-balaraman** [comment]
@rattrayalex it is fixed and released in version 0.4.0

**Comment by rattrayalex** [comment]
Awesome ty!
